### ISSUE TITLE
Possible bug with onBeforeVersionedPublish

### ISSUE THREAD

**Issue by sanderha** [symbiote/silverstripe-datachange-tracker#11]
Hello

It seems when I change fields on a page and publish, the "Before" and "After" fields on the generated ```DataChangeRecord ``` is always set to "null". And the ChangeType is always "Publish Stage to Live".

If I remove ``` ChangeRecordable::onBeforeVersionedPublish() ``` it all works as intended, change type is "Change" and before & after are correctly written.

I havent had time to debug this properly, just wanted to let you know

**Comment by silbinarywolf** [comment]
Thanks for the heads up, sorry you got no reply.
