### ISSUE TITLE
'Published States' gridfield can soemtimes display colliding ClassID objects

### ISSUE THREAD

**Issue by stephenmcm** [symbiote/silverstripe-datachange-tracker#14]
The 'Published States' gridfield only checks ClassID so can sometimes display objects that have colliding IDs.

https://github.com/silverstripe-australia/silverstripe-datachange-tracker/blob/master/code/extensions/SiteTreeChangeRecordable.php#L22

**Comment by silbinarywolf** [comment]
@stephenmcm Can you please be more descriptive of what this problem is? Is it still an issue?

**Comment by nglasl** [comment]
Closing this one due to activity. Please open this again if it remains an issue.
