### ISSUE TITLE
Fatal error: in .yml file

### ISSUE THREAD

**Issue by adrian-stein** [symbiote/silverstripe-datachange-tracker#33]
Tring to install and it does not work. I get this error:
`Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: The reserved indicator "%" cannot start a plain scalar; you need to quote the scalar at line 6 (near "dataChangeTrackService: %$DataChangeTrackService"). in \vendor\symfony\yaml\Inline.php on line 307`

It looks like you need to wrap any % signs in yml files in quotes.

So something like this: 

```
---
Name: datachange_injector_config
---
SilverStripe\Core\Injector\Injector:
  DataChangeTrackService:
    class: \Symbiote\DataChange\Service\DataChangeTrackService
  Symbiote\DataChange\Extension\ChangeRecordable:
    properties:
      dataChangeTrackService: '%$DataChangeTrackService'
  Symbiote\DataChange\Extension\SiteTreeChangeRecordable:
    properties:
      dataChangeTrackService: '%$DataChangeTrackService'
```

Can you quickly fix it up please :)

**Comment by samandeggs** [comment]
I have the same issue - has been a thing in SS build for a while.

**Comment by samandeggs** [comment]
Have created PR #34 which solves this

**Comment by nyeholt** [comment]
Done
